// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6oQxpDoYK_y1CP1d9jAZn6-E8LaeyAM',
    appId: '1:924982588624:web:dedddb0dbe27541ad29ad5',
    messagingSenderId: '924982588624',
    projectId: 'flutter-project-373d0',
    authDomain: 'flutter-project-373d0.firebaseapp.com',
    storageBucket: 'flutter-project-373d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWrtQ6Gvu_MuVwMJVDTUQziQs76Kcte2A',
    appId: '1:924982588624:android:42ffc654233bfcdbd29ad5',
    messagingSenderId: '924982588624',
    projectId: 'flutter-project-373d0',
    storageBucket: 'flutter-project-373d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NpY__J5k9Kjsn8RTil3uzV1W6_TxA_s',
    appId: '1:924982588624:ios:d4f59e701a61d09dd29ad5',
    messagingSenderId: '924982588624',
    projectId: 'flutter-project-373d0',
    storageBucket: 'flutter-project-373d0.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0NpY__J5k9Kjsn8RTil3uzV1W6_TxA_s',
    appId: '1:924982588624:ios:d4f59e701a61d09dd29ad5',
    messagingSenderId: '924982588624',
    projectId: 'flutter-project-373d0',
    storageBucket: 'flutter-project-373d0.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu6oQxpDoYK_y1CP1d9jAZn6-E8LaeyAM',
    appId: '1:924982588624:web:4b692cf304ed77efd29ad5',
    messagingSenderId: '924982588624',
    projectId: 'flutter-project-373d0',
    authDomain: 'flutter-project-373d0.firebaseapp.com',
    storageBucket: 'flutter-project-373d0.appspot.com',
  );
}
